-- ======================================================
-- 自动生成的路径修复SQL (由 fuzzy_match_paths.py 生成)
-- 生成时间: 2026-07-12
-- 匹配成功: 54 条 | 未匹配(清空): 94 条
-- ⚠️  请先检查报告确认无误后再执行！
-- ======================================================

BEGIN TRANSACTION;

-- ---------- 匹配成功: 更新为 hhp 实际路径 ----------
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\FSDSS-710-天使萌-有码-【末班车没了的话就来我家吧！】要是我没这么说就好了... 后辈男的猎奇性欲.mp4' WHERE numbers_name = 'FSDSS-710-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\FSDSS-968 [自提征用]性爱教主天使もえ与信徒们过着淫乱的集体生活 天使萌.mp4' WHERE numbers_name = 'FSDSS-968-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\HMN-701-香水纯-有码-青梅因女仆咖啡震怒 只能反复打桩内射.mp4' WHERE numbers_name = 'HMN-701-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\HMN-751-香水纯-有码-学校泳装中出训练 新任女教师十年来首次穿学校泳装，被迫将双腿向上滑动，精液飞溅，湿透。.mp4' WHERE numbers_name = 'HMN-751-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\IPX-660-桃乃木かな-有码-不想被发现那就把内裤脱了 偷盗少女 射多少发都不放她走 追击活塞强奸的悲剧 桃乃木加奈.mp4' WHERE numbers_name = 'IPX-660 不想被发现那就把内裤脱了 偷盗少女 射多少发都不放她走 追击活塞强奸的悲剧 桃乃木';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\ipx-776-楓カレン &nbsp; &nbsp; &nbsp; &nbsp;-有码-身体代偿肉便器 被射多少次 都不会结束 绝伦黑道大叔的10天监禁生活 时间轴修正版.mp4' WHERE numbers_name = 'IPX-776-UC';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\IPX-934-桃乃木加奈-有码-【今天请忘记你老婆】和情人一年后再会 珍惜每分每秒的出差时间(完整版).mp4' WHERE numbers_name = 'IPX-934 【今天请忘记你老婆】和情人一年后再会 珍惜每分每秒的出差时间(完整';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\IPX-998-C.mp4' WHERE numbers_name = 'IPX-998 【自提征用】老师…今天可以过夜吗？实习中住旅馆的我，被学生近逼而意外同房… 相-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\IPZZ-077 [自提征用]和美女交换唾液 口水横流的浓厚接吻SEX 三上悠亚.mp4' WHERE numbers_name = 'IPZZ-077-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\IPZZ-240 [自译征用]被討厭的男主管玩弄 可是他的雞雞太舒服了…被灌醉醒來之後竟然在飯店裡… 楓可憐.mp4' WHERE numbers_name = 'IPZZ-240-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\90分\\IPZZ-641-佐佐木纱希-有码-最讨厌的继父最喜欢的竟然是我&amp;hellip;一边被侵犯一边高潮的最大屈辱强姦.mp4' WHERE numbers_name = 'IPZZ-641-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\IPZZ-683-佐木さき-有码-迷人的嘴唇唾液沾满舔嘴肮脏的小恶魔女人.mp4' WHERE numbers_name = 'IPZZ-683-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\90分\\IPZZ-727-佐佐木纱希-有码-淫女学生捉弄老师 深喉口交做爱.mp4' WHERE numbers_name = 'IPZZ-727-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\JUR-648-新妻优香-无码-朋友炫耀说和老婆一周干三次 那我就每周干她五次 合计内射二十发 把那家伙的老婆搞走了.mp4' WHERE numbers_name = 'JUR-648-UC';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIAA-444-松本いちか-有码-这么狂妄的小屁孩 用活塞运动让她长长见识 松本一花.mp4' WHERE numbers_name = 'MIAA-444 这么狂妄的小屁孩 用活塞运动让她长长见识 松本';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIDA-072 [自提征用]惊天独家 八木奈奈设下色诱陷阱 反被搭讪达人带回家 八木奈奈.mp4' WHERE numbers_name = 'MIDA-072-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIDA-154-新有菜-有码-水手服学校泳衣灯笼裤裸色丝带。青春复仇记：用不尽的活塞买成人中出.mp4' WHERE numbers_name = 'MIDA-154-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\90分\\MIDA-257-石川澪-有码-毕业瞬间的空教室里，我要与澪狂野交媾直到她淫乱失神！即使被她用处女膜的甜腻挑逗整整一年地折磨！.mp4' WHERE numbers_name = 'MIDA-257-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIDA-304-石川澪-有码-错过末班车住我家 酒瘾没过足的澪前辈和我玩的嗨翻天，干到早上起不来.mp4' WHERE numbers_name = 'MIDA-304-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\489155.com@MIDA-583-C.mp4' WHERE numbers_name = 'MIDA-583-UC';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIDV-250-八木奈奈-有码-沉默寡言的义姐 无自觉的巨尻诱惑 无法忍耐后的暴走后入活塞.mp4' WHERE numbers_name = 'MIDV-250-UC';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIDV-375-八木奈奈-有码-被住在垃圾屋里的异臭大叔监禁 五天的同居调教记录.mp4' WHERE numbers_name = 'MIDV-375-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIDV-640 [自提征用]要不要在前辈家重新喝一杯？在黑丝袜后辈女职员的撒娇 宮下玲奈.mp4' WHERE numbers_name = 'MIDV-640-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIDV-670 [自提征用]在老家的乡下嫉妒我东京女友的青梅竹马澪 大汗淋漓并且说着淫语让我射精 石川澪.mp4' WHERE numbers_name = 'MIDV-670-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIDV-835 [自提征用]为了还债禽兽父亲让继女肉偿 结果女儿堕落了 石川澪.mp4' WHERE numbers_name = 'MIDV-835-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIDV-946 [自提征用]周日早上醒来可爱的小澪就跟我干一整天，没有从兴奋中冷静下来。石川澪.mp4' WHERE numbers_name = 'MIDV-946-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\MIH-016-松本一香-有码-耳边说着爸爸这个杂鱼的同时舔耳抽插内射做爱.mp4' WHERE numbers_name = 'MIH-016-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\PPPE-401-楪可怜-有码-在“妹妹归哥哥所有”的乡下陋习下，妹妹成了专属于我的射精助理，巨乳义妹内射十次的暑假日记。.mp4' WHERE numbers_name = 'PPPE-401-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SNOS-034-白上咲花-有码-我想利用女学生的孤独舔舐她 - 这个孤独的女学生即使被班主任强奸也很开心。.mp4' WHERE numbers_name = 'SNOS-034-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\90分\\SONE-192-早坂姬-有码-女友的妹妹是知名抖音網紅 每次在網路上看到的姬 被她痴女玩弄 不去工作猛烈打炮 女友不在的兩天紀錄。.mp4' WHERE numbers_name = 'SONE-192-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SONE-272-浅野こころ-有码-年末年初，大学生宿舍里只有一个女学生和一个叔叔经理...... 一个饥渴的中年男人 ● 一个空虚寂寞的年轻女孩 ● 这太相配了.mp4' WHERE numbers_name = 'SONE-272-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\90分\\SONE-405 [自提征用]教职人生27年 被最美的女学生求爱诱惑 我的人生即将要毁了 河北彩花.mp4' WHERE numbers_name = 'SONE-405-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\90分\\SONE-407--无码-巨乳前辈 夺走了我的处子之身 Unpai.mp4' WHERE numbers_name = 'SONE-407-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SONE-456-Unpai-有码-今天我是一个受虐宠物肉玩具，专供贪婪的男人使用。.mp4' WHERE numbers_name = 'SONE-456-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SONE-543 [自提征用]在爱人面前被侵犯的背德感 可能在公司内暴露的刺激 河北彩伽.mp4' WHERE numbers_name = 'SONE-543-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SONE-732-白上咲花-有码-我的小妹妹，不久前曾和我一起玩摔跤，但最近她经常露出内裤。大哥你会怎么做……？我们走吧！ ？.mp4' WHERE numbers_name = 'SONE-732-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\90分\\SONE-763-河北彩花-有码-被外表清纯私下是欲女的图书管理员足交M调教的我.mp4' WHERE numbers_name = 'SONE-763-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SONE-830-：看著想同居来看房的幸福情侣，越是甜蜜越激起NTR她男友的慾望，我身为房仲小姐却专偷男人肉棒 【出演女优】：miru-有码-：看著想同居来看房的幸福情侣，越是甜蜜越激起NTR她男友的慾望，我身为房仲小姐却专偷男人肉棒 【出演女优】：miru.mp4' WHERE numbers_name = 'SONE-830-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SONE-853-河北彩伽-有码-烟花大会之夜，一直互相暗恋的我们终于结合，仿佛要倾泻积攒了十几年的爱意般贪婪地索求着彼此的身体.mp4' WHERE numbers_name = 'SONE-853-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SSIS-241-三上悠亜 &nbsp; &nbsp; &nbsp; &nbsp;-有码-成为教师后感受到的 真挚纯爱 三上悠亚.mp4' WHERE numbers_name = 'SSIS-241 成为教师后感受到的 真挚纯爱 三上';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SSIS-365-三上悠亚-无码-三上悠亚的一整月密着拍摄 稍有缝隙就即刻做爱.mp4' WHERE numbers_name = 'SSIS-365 【诶！要在这里做吗？】三上悠亚的一整月密着拍摄 稍有缝隙就即刻做';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SSIS-586-C.mp4' WHERE numbers_name = 'SSIS-586 【自译征用】在出差处被性骚扰上司安排共处一室... 直到早 河北-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SSIS-659-香水纯-无码-处男的我被文学部的痴女学妹香水纯吃掉了.mp4' WHERE numbers_name = 'SSIS-659 【自提征用】FANZA排行榜24小时第一 周榜第一 月榜第一  香-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\SSIS-663-三上悠亚-无码-隐退发表 126天后 不再是AV女优.mp4' WHERE numbers_name = 'SSIS-663-UC';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\85分\\SSIS-723 [自提征用]人气风俗女香水纯让我恍惚都是口水的性爱生活。香水纯.mp4' WHERE numbers_name = 'SSIS-723-UC';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\90分\\SSIS-795 [自提征用]被偷偷媚药浸渍的七天后 像嗑药一般的bitch 三上悠亚.mp4' WHERE numbers_name = 'SSIS-795-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\ssni-989-三上悠亜 &nbsp; &nbsp; &nbsp; &nbsp;-有码-想不到在出差地和最讨厌的性骚上司同房投宿被绝赞黏着抽插干得整晚持续高潮的巨乳OL三上悠亚修正版.mp4' WHERE numbers_name = 'SSNI-989-UC';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\STARS-998 [自提征用]本庄鈴跟素人男生一起濃厚喝精子紀錄片.mp4' WHERE numbers_name = 'STARS-998-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\START-036-本庄铃-有码-从丈夫葬礼的第二天开始 被无赖的公公强行内射怀孕的寡妇.mp4' WHERE numbers_name = 'START-036-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\START-237 [自提征用]“结婚已经四年了，老婆第一次不回家背着我勾引别的男人！ 神木麗.mp4' WHERE numbers_name = 'START-237-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\START-326-神木丽-有码-和高冷的女上司出差后才知道原来她是个骚到极致的女人.mp4' WHERE numbers_name = 'START-326-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\START-542-神木麗-有码-公司女主管邀请我喝酒，当我听她抱怨时，她变成了情绪不稳定的女人，最后她竟然求我进行无套性行为.mp4' WHERE numbers_name = 'START-542-C';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\IPX-666-相沢みなみ-有码-【没车坐了就来我家吧】明明家里恋人在等我 我却错过末班车到女同事的家里借宿 无内的她和我整晚的绝伦性爱 相泽南.mp4' WHERE numbers_name = 'ipx-666 明明家里恋人在等我却错过末班车到女同事相泽南的家里借宿整晚的绝伦性爱修正时';
UPDATE av SET local_path = 'Z:\\115open\\hhp\\80分\\ssis-338-C.mp4' WHERE numbers_name = 'ssis-338  最好的情人 :既不干涉工作也不干涉家庭，只追求性爱的理想关系 三上';

-- ---------- 未匹配: 清空失效路径 ----------
UPDATE av SET local_path = NULL WHERE numbers_name = 'ABF-090-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'ABW-283-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'ADN-451  【自提征用】一旦答应 义父仅十秒的插入... 相性拔群 直接绝顶的我 三-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'ADN-568-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'ATID-522 为了帮异常性欲的哥哥消解 被母亲拜托每日性处理 明';
UPDATE av SET local_path = NULL WHERE numbers_name = 'DASS-329-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'FC2PPV-3363283-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'FC2PPV-3518061-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'FSDSS-209 肉欲 本能 腔感 觉醒性交 桥本';
UPDATE av SET local_path = NULL WHERE numbers_name = 'FSDSS-361 【自提征用】在社交平台晒出裸体的女子 好像就是住在隔壁的... 天-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPX-680-UC';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPX-766-UC';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPX-778  洗脑 肉体完全被征服的人气女播音员 催眠疗法强制失禁 潮喷(完整';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPX-850 出差处的破纪录暴雨 和处男部下突然处于共处一室的情况... 被雨打湿的';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPX-889 新入社员欢迎会 喝得烂醉的我被公司的前台小姐带到酒店 直到早晨的榨精 相';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPX-906 口交护士的彻底射精管理 相';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPX-922 变态公公的扭曲NTR用不断舔舐的舌技让儿媳相泽南不断高潮（完整字幕';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPX-939 为了保护弟弟美女姐姐相泽南被无恶不作的大叔监禁以身偿还变成肉便器绝伦射精十天的生活（完整字幕';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPX-973 【自提征用】和最喜欢SEX的姐姐在郊外酒店 一起迎来早晨 痴女document24-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPX-981-UC';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPZZ-024-UC';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPZZ-054-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'IPZZ-474-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'JUR-205-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDA-008-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDA-040-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDA-063-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDA-368-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDA-463-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDE-923 青春期女孩的家庭教师在100天后 完全反过来被调教的我 七泽';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDE-928 那个夏天 和搜查中的巨乳前辈交融体液... 高桥';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-234  【自提征用】“现在已经高潮了所以别动！”状态下依旧持续让她高潮4小时-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-248 【自提征用】泡浴社新学生会长澪穿淫装大奋斗。无限发射服务 石-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-266 【自提征用】被女友闺蜜告白的我 宫下-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-518-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-531-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-611-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-699-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-751-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-787-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-872-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'MIDV-881-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SAME-032 【自提征用】被迫肉体奉仕的小偷人妻 三-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SNIS-270【自译征用】和小萌的同居性生活 天-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-031-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-082-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-114-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-122-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-230-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-466-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-573-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-619-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-692-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-706-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SONE-785-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SSIS-287 流口水 高潮脸 失禁 一并解放 三上悠亚的';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SSIS-518 170cm完美比例 枫风华（21岁）做爱直拍 心跳都能听到的近距离SEX（完整字幕';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SSIS-531 人生第一次 绝顶高潮 超越高潮 河北';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SSIS-573-UC';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SSIS-617 【自提征用】漏液射精 无视贤者时间！让你无限射精的高潮沙龙 mi-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'SSNI-520-UC';
UPDATE av SET local_path = NULL WHERE numbers_name = 'STAR-821 户田真琴 临近结婚 被患者跟踪的护士 榎本';
UPDATE av SET local_path = NULL WHERE numbers_name = 'STARS-380 当天往返的12发射精中出温泉旅行 青';
UPDATE av SET local_path = NULL WHERE numbers_name = 'STARS-818-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'STARS-870-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'START-057-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'START-169-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'START-242-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'START-255-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'START-353-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'START-364-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'START-539-C';
UPDATE av SET local_path = NULL WHERE numbers_name = 'fsdss-289 辍学在风俗店上班的超可爱长腿青梅竹马桥本有菜被家人发现闹掰后离家出走跑到我这里';
UPDATE av SET local_path = NULL WHERE numbers_name = 'ipx-643 替身肉便器射精也射精不完与绝伦黑帮大叔的10天监禁生活 桃乃木';
UPDATE av SET local_path = NULL WHERE numbers_name = 'ssis-032 发现最讨厌的女上司在粉色沙龙做兼职后立场逆转强按着让她口交强行';
UPDATE av SET local_path = NULL WHERE numbers_name = 'ssis-133 同期进公司的同事成了接吻狂“你讨厌我吗？”mi';
UPDATE av SET local_path = NULL WHERE numbers_name = 'stars-326 女友的妹妹洗完澡后无内衣的姿态让我忍不住勃起 却被丰满的她数次要求中出青空光时间轴修';
UPDATE av SET local_path = NULL WHERE numbers_name = 'stars-345 和处男部下在出差处共处一室 直到第二天早上的浓厚相奸 化妆品厂商的NTR女上司 本庄铃 音视频同步';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1186';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1187';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1188';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1189';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1197';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1200';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1201';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1301';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1570';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1595';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1665';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1668';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1670';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1741';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-1742';
UPDATE av SET local_path = NULL WHERE numbers_name = 'zzz-968';

COMMIT;
